name: Bump Patch Version

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  bump-patch:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # serve per creare commit / tag

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Frontend bump patch version
        run: |
          cd ./my-financial-dashboard
          npm install
          NEW_VERSION=`npm version patch -m "build: bump patch to %s"`
          echo "Version updated to ${NEW_VERSION}"
          # Set a variable to use it in another step
          echo "new_frontend_version=${NEW_VERSION}" >> "$GITHUB_ENV"

      - name: Frontend bump patch version
        run: |
          cd ./my-backend-dashboard
          npm install
          NEW_VERSION=`npm version patch -m "build: bump patch to %s"`
          echo "Version updated to ${NEW_VERSION}"
          # Set a variable to use it in another step
          echo "new_backend_version=${NEW_VERSION}" >> "$GITHUB_ENV"

      # Push commit e tag
      - name: Commit changes
        run: |
          git config --global user.email "a.acquavia@studenti.unipi.com"
          git config --global user.name "thorongil05"
          git add ./my-financial-dashboard/*
          git add ./my-financial-backend/*
          git commit -m "build: update to version $new_frontend_version - $new_backend_version"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}